language: Java
jdk:
  - oraclejdk8
install: mvn -q clean -DskipTests -DskipITs install && mvn -q clean cobertura:cobertura-integration-test coveralls:report
script: mvn -q clean verify && mvn -q clean cobertura:cobertura-integration-test coveralls:report
