sudo: false
language: Java
jdk:
  - oraclejdk8
before_install: export "MAVEN_OPTS=$MAVEN_OPTS -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
install: mvn -B clean install -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
script: mvn -B cobertura:cobertura-integration-test coveralls:report -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
