language: Java
jdk:
  - oraclejdk8
install: travis_wait mvn -q clean -DskipTests -DskipITs install
script: mvn -q clean verify
after_success:
  - mvn -q clean cobertura:cobertura-integration-test coveralls:report
